-- Ejecutar una vez en Supabase SQL Editor después de supabase-schema.sql

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'paid', 'trial')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  status text not null default 'free',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.usage_events enable row level security;
alter table public.subscriptions enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

create policy "Users can read their own profile" on public.profiles for select
  using (auth.uid() = id or public.is_admin());
create policy "Users can create their own profile" on public.profiles for insert
  with check (auth.uid() = id and role = 'user');
create policy "Admins can update profiles" on public.profiles for update
  using (public.is_admin()) with check (public.is_admin());
create policy "Users can create their own usage events" on public.usage_events for insert
  with check (auth.uid() = user_id);
create policy "Admins can read usage events" on public.usage_events for select
  using (public.is_admin());
create policy "Users can read their own subscription" on public.subscriptions for select
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  insert into public.subscriptions (user_id) values (new.id) on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Tras crear tu cuenta, ejecuta sustituyendo TU_EMAIL:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'TU_EMAIL');
