-- Ejecutar una vez en Supabase SQL Editor después de supabase-schema.sql

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'paid', 'trial')),
  status text not null default 'active' check (status in ('active', 'suspended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists status text not null default 'active';

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  status text not null default 'free',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.usage_events enable row level security;
alter table public.subscriptions enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable
as $$ select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'); $$;

drop policy if exists "Users can read their own profile" on public.profiles;
create policy "Users can read their own profile" on public.profiles for select
  using (auth.uid() = id or public.is_admin());
drop policy if exists "Users can create their own profile" on public.profiles;
create policy "Users can create their own profile" on public.profiles for insert
  with check (auth.uid() = id and role = 'user');
drop policy if exists "Admins can update profiles" on public.profiles;
create policy "Admins can update profiles" on public.profiles for update
  using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Users can create their own usage events" on public.usage_events;
create policy "Users can create their own usage events" on public.usage_events for insert
  with check (auth.uid() = user_id);
drop policy if exists "Admins can read usage events" on public.usage_events;
create policy "Admins can read usage events" on public.usage_events for select
  using (public.is_admin());
drop policy if exists "Users can read their own subscription" on public.subscriptions;
create policy "Users can read their own subscription" on public.subscriptions for select
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  insert into public.subscriptions (user_id) values (new.id) on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

drop function if exists public.admin_list_users();
create or replace function public.admin_list_users()
returns table (
  id uuid,
  email text,
  display_name text,
  role text,
  plan text,
  status text,
  activity_count bigint,
  task_count bigint,
  test_count bigint,
  note_count bigint,
  last_activity timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  return query
    select p.id, u.email::text, p.display_name, p.role, p.plan, p.status,
      (select count(*) from public.usage_events e where e.user_id = p.id) as activity_count,
      (select count(*) from public.tasks t where t.user_id = p.id) as task_count,
      (select count(*) from public.tests t where t.user_id = p.id) as test_count,
      (select count(*) from public.notes n where n.user_id = p.id) as note_count,
      (select max(e.created_at) from public.usage_events e where e.user_id = p.id) as last_activity
    from public.profiles p
    join auth.users u on u.id = p.id
    order by p.created_at asc;
end;
$$;

create or replace function public.admin_update_user(target_user_id uuid, new_role text, new_plan text, new_status text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  if new_role not in ('user', 'admin') or new_plan not in ('free', 'trial', 'paid') or new_status not in ('active', 'suspended') then raise exception 'invalid values'; end if;
  if target_user_id = auth.uid() and new_role <> 'admin' then raise exception 'cannot remove your own admin role'; end if;
  update public.profiles set role = new_role, plan = new_plan, status = new_status, updated_at = now() where id = target_user_id;
end;
$$;

create or replace function public.admin_delete_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  if target_user_id = auth.uid() then raise exception 'cannot delete yourself'; end if;
  delete from auth.users where id = target_user_id;
end;
$$;

grant execute on function public.admin_list_users() to authenticated;
grant execute on function public.admin_update_user(uuid, text, text, text) to authenticated;
grant execute on function public.admin_delete_user(uuid) to authenticated;

-- Tras crear tu cuenta, ejecuta sustituyendo TU_EMAIL:
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'TU_EMAIL');
