-- StudyFlow: esquema multiusuario para Supabase
-- Ejecuta este archivo en Supabase > SQL Editor > New query.

create table if not exists public.tasks (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  subject text not null,
  duration integer not null default 45 check (duration >= 0 and duration <= 720),
  date date not null,
  start_time time not null default '09:00',
  priority text not null default 'Media',
  status text not null default 'planificado',
  completed boolean not null default false,
  difficulty text not null default 'media',
  needs_review boolean not null default false,
  is_class boolean not null default false,
  type text not null default 'study',
  actual_minutes integer not null default 0 check (actual_minutes >= 0),
  focus_sessions jsonb not null default '[]'::jsonb,
  completion_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tests (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  date date not null,
  correct integer not null default 0 check (correct >= 0),
  incorrect integer not null default 0 check (incorrect >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.notes (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  subject text not null,
  topic text not null default 'General',
  task_id text,
  text text not null,
  date date not null,
  difficulty text not null default 'media',
  needs_review boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.tasks enable row level security;
alter table public.tests enable row level security;
alter table public.notes enable row level security;

create policy "Users can manage their own tasks"
  on public.tasks for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can manage their own tests"
  on public.tests for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can manage their own notes"
  on public.notes for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists tasks_user_date_idx on public.tasks(user_id, date);
create index if not exists tests_user_date_idx on public.tests(user_id, date);
create index if not exists notes_user_date_idx on public.notes(user_id, date);

-- Perfiles y administración segura
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'user' check (role in ('user', 'admin')),
  plan text not null default 'free' check (plan in ('free', 'paid', 'trial')),
  must_change_password boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  provider text,
  provider_customer_id text,
  provider_subscription_id text,
  status text not null default 'free',
  current_period_end timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.usage_events enable row level security;
alter table public.subscriptions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create policy "Users can read their own profile"
  on public.profiles for select
  using (auth.uid() = id or public.is_admin());

create policy "Users can create their own profile"
  on public.profiles for insert
  with check (auth.uid() = id and role = 'user');

create policy "Admins can update profiles"
  on public.profiles for update
  using (public.is_admin())
  with check (public.is_admin());

create policy "Users can create their own usage events"
  on public.usage_events for insert
  with check (auth.uid() = user_id);

create policy "Admins can read usage events"
  on public.usage_events for select
  using (public.is_admin());

create policy "Users can manage their own subscription"
  on public.subscriptions for select
  using (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  insert into public.subscriptions (user_id)
  values (new.id)
  on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.clear_password_change_requirement()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles
  set must_change_password = false, updated_at = now()
  where id = auth.uid();
end;
$$;

grant execute on function public.clear_password_change_requirement() to authenticated;

-- Tras ejecutar este esquema, convierte tu cuenta en administradora sustituyendo el email.
-- update public.profiles set role = 'admin' where id = (select id from auth.users where email = 'TU_EMAIL');
